/**
 * Database Koleksi Antik Istana Degan (Udien Barang Antique Semarang)
 * Disesuaikan dengan kurasi asli feed Instagram @istanadegan milik Pak Tahrudin
 */

const ANTIQUE_COLLECTIONS = [
  {
    id: "IDG-001",
    title: "Pasang Jam Dinding Antik Kayu Jati Klasik Eropa / Dutch Vintage Wall Clock",
    category: "jam-kuno",
    categoryLabel: "Jam Antik",
    era: "Awal Abad ke-20 / Dutch Vintage / Era Kolonial Eropa",
    condition: "Mesin masih berfungsi, patina kayu alami dan detail antik terawat",
    dimension: "Tinggi sekitar 95-110 cm, Lebar 38-45 cm (satu unit)",
    price: "Tanya Harga / Nego",
    status: "Terkurasi",
    statusType: "curated",
    image: "img/p01.png",
    description: "Sepasang jam dinding antik bergaya Eropa klasik dengan bodi kayu solid berukiran tegas, dial kuningan vintage, dan detail ornamen arsitektur yang kuat. Tampilan ini sangat cocok untuk ruang tamu, foyer, atau ruangan bergaya kolonial dengan nuansa antik yang otentik. Jam ini menyimpan karakter historis tinggi dan menjadi pilihan utama kolektor interior vintage.",
    highlights: [
      "Bentuk bodi kayu antik dengan ukiran khas Eropa klasik",
      "Dial kuningan vintage dengan angka dan skala autentik",
      "Mesin mekanik antik, cocok untuk koleksi serta dekorasi ruang",
      "Patina kayu alami dan detail arsitektur yang kuat",
      "Cocok untuk interior kolonial, vintage, atau galeri antik"
    ]
  },
  {
    id: "IDG-002",
    title: "Set Miniatur Kincir Angin Keramik Biru Putih (Delft Blue Style)",
    category: "keramik",
    categoryLabel: "Keramik & Porselen",
    era: "Klasik Eropa / Dutch Vintage Style",
    condition: "Glosir mengkilap, 100% mulus tanpa gompal",
    dimension: "Tinggi bervariasi 12 - 18 cm (Set 4 Pcs)",
    price: "Tanya Harga / Nego",
    status: "Tersedia",
    statusType: "available",
    image: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80",
    description: "Set koleksi miniatur kincir angin khas Belanda dengan motif lukisan kobalt biru putih legendaris (Delftware). Kincir dapat diputar, bagian bawah terdapat mark cap khas keramik lawas. Sangat menawan untuk pajangan lemari kaca atau buffet ruang tamu antik.",
    highlights: ["Satu set lengkap 4 ukuran berjenjang", "Baling-baling orisinal berfungsi", "Glasir porselen putih kebiruan vintage"]
  },
  {
    id: "IDG-003",
    title: "Plang Reklame Enamel Kuno 'Gargoyle Mobiloil' Orisinal",
    category: "reklame",
    categoryLabel: "Plang & Reklame Jadul",
    era: "Era Kolonial Hindia Belanda (c. 1930-1940s)",
    condition: "Patina alami bersejarah, enamel tebal timbul",
    dimension: "65 cm x 45 cm",
    price: "Kolektor Item (Hubungi Pemilik)",
    status: "Tersedia",
    statusType: "available",
    image: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80",
    description: "Plang papan iklan enamel timbul langka peninggalan era pompa bensin kolonial bertuliskan 'Gargoyle Mobiloil - Make the chart your guide'. Salah satu buruan tertinggi kolektor otomotif lawas di Indonesia. Bahan plat besi sangat tebal dengan tekstur enamel otentik.",
    highlights: ["Original vintage patina (bukan repro)", "Plat besi tebal antik berbobot", "Cat timbul enamel-baked khas era 30an"]
  },
  {
    id: "IDG-004",
    title: "Ornamen Kaki Meja Antik Besi Cor Relief Kepala Singa",
    category: "besi-kuno",
    categoryLabel: "Besi Cor & Arsitektur",
    era: "Awal Abad ke-20 (Art Deco / Victorian)",
    condition: "Besi cor utuh padat, bebas keropos",
    dimension: "Tinggi 74 cm, Lebar 48 cm, Bobot ~18 kg",
    price: "Tanya Harga / Nego",
    status: "Tersedia",
    statusType: "available",
    image: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80",
    description: "Sepasang penyangga kaki meja besi cor (cast iron) dengan relief kepala singa dan ornamen salib salur klasik. Cocok dipadukan dengan daun meja kayu jati utuh atau marmer kuno untuk ruang makan bernuansa kolonial istimewa.",
    highlights: ["Besi cor tebal sangat kokoh", "Detail ukir singa tegas dan berkarakter", "Finishing patina dark bronze alami"]
  },
  {
    id: "IDG-005",
    title: "Sepasang Patung Ksatria & Bangsawan Perunggu Kolonial",
    category: "seni-ukir",
    categoryLabel: "Seni & Ukiran",
    era: "Eropa Klasik (Vintage)",
    condition: "Perunggu berat terawat, detail pakaian tajam",
    dimension: "Tinggi 55 cm / patung",
    price: "Kolektor Item",
    status: "Tersedia",
    statusType: "available",
    image: "https://images.unsplash.com/photo-1544531585-9847b68c8c86?auto=format&fit=crop&w=800&q=80",
    description: "Sepasang patung figur bangsawan dan prajurit Eropa berbahan logam padat dengan detail baju zirah, topi berbulu, dan tombak. Biasa ditempatkan di atas perapian, foyer pintu masuk, atau meja konsol galeri.",
    highlights: ["Detail anatomi dan ornamen pakaian sangat presisi", "Bobot mantap dan kokoh", "Warna oksidasi perunggu gelap otentik"]
  },
  {
    id: "IDG-006",
    title: "Roster Keramik Glasir Hijau Koin Kuno Dinasti (Set Antik)",
    category: "besi-kuno",
    categoryLabel: "Besi Cor & Arsitektur",
    era: "Peranakan Tionghoa Jawa Klasik",
    condition: "Glasir mengkilap lumut, utuh terawat",
    dimension: "20 cm x 20 cm x 5 cm per keping",
    price: "Rp 150.000 / keping (Nego Partai)",
    status: "Tersedia",
    statusType: "available",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
    description: "Roster ventilasi keramik glasir hijau zamrud motif koin keberuntungan peranakan kuno. Sangat diburu oleh arsitek dan desainer interior untuk ornamen dinding fasad rumah heritage, villa, atau kafe bergaya vintage klasik.",
    highlights: ["Glasir hijau antik orisinal", "Bahan keramik bakar tahan cuaca puluhan tahun", "Stok tersedia puluhan keping siap pasang"]
  },
  {
    id: "IDG-007",
    title: "Jam Dinding Antik Kayu Jati Bandul Kuningan Tiga Lubang",
    category: "jam-kuno",
    categoryLabel: "Jam Antik",
    era: "Junghans / Mauthe Jerman (c. 1950)",
    condition: "Mesin hidup normal, dentang merdu per jam",
    dimension: "Tinggi 80 cm, Lebar 34 cm",
    price: "Tanya Harga / Nego",
    status: "Terkurasi",
    statusType: "curated",
    image: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80",
    description: "Jam dinding kayu jati pekat orisinal dengan jendela kaca patri berbevel. Menggunakan mesin mekanik bandul kuningan 3 lubang dengan senar melodi Westminster yang berdenting jernih setiap 15 menit dan tepat jam.",
    highlights: ["Mesin orisinal buatan Jerman terawat", "Kunci putar dan bandul kuningan lengkap", "Box kayu jati kokoh tanpa keropos"]
  },
  {
    id: "IDG-008",
    title: "Mangkok & Piring Keramik Tegal Gendoe Motif Bunga Lawasan",
    category: "keramik",
    categoryLabel: "Keramik & Porselen",
    era: "Era Awal 1900-an",
    condition: "Crackling alami usia (crazing) artistik, tanpa retak fatal",
    dimension: "Diameter piring 24 cm, mangkok 18 cm",
    price: "Tanya Harga / Nego",
    status: "Tersedia",
    statusType: "available",
    image: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=800&q=80",
    description: "Koleksi piring dan mangkok porselen jadul 'Tegal Gendoe' dengan corak lukis tangan motif flora percampuran budaya pesisiran Jawa dan Tionghoa. Memiliki nilai historis tinggi bagi penggemar kuliner dan tableware masa lampau.",
    highlights: ["Lukisan tangan (hand-painted) orisinal", "Tanda crackle glasir antik otentik", "Koleksi langka di pasaran"]
  },
  {
    id: "IDG-009",
    title: "Lampu Gantung Minyak Semprong Antik Kerek Kuningan Jawa",
    category: "besi-kuno",
    categoryLabel: "Besi Cor & Arsitektur",
    era: "Hindia Belanda / Jawa Tradisional",
    condition: "Rangka kuningan utuh, kap opal putih mulus",
    dimension: "Diameter kap 40 cm, Rantai kerek 120 cm",
    price: "Tanya Harga / Nego",
    status: "Tersedia",
    statusType: "available",
    image: "https://images.unsplash.com/photo-1540932239986-30128078f3c5?auto=format&fit=crop&w=800&q=80",
    description: "Lampu gantung antik model kerek (katrol timbel) berbahan kuningan tempa dengan kap kaca susu opal putih. Sudah dimodifikasi fitting lampu listrik tersembunyi sehingga siap pakai menerangi pendopo, ruang tamu, atau teras rumah klasik.",
    highlights: ["Bandul timbel pengatur ketinggian berfungsi", "Kap kaca opal tebal orisinal", "Bahan kuningan berpatina indah"]
  }
];

// Data informasi profil Pak Tahrudin & Istana Degan
const STORE_PROFILE = {
  name: "Istana Degan",
  badgeName: "Udien Barang Antique",
  owner: "Pak Tahrudin",
  phone: "085640001142",
  phoneDisplay: "0856-4000-1142",
  waNumberClean: "6285640001142",
  bankName: "BCA (Bank Central Asia)",
  bankAccount: "TAHRUDIN",
  bankNote: "PENTING: Transaksi resmi HANYA menggunakan rekening BCA atas nama TAHRUDIN. Selain itu dipastikan BUKAN milik kami.",
  instagram: "@istanadegan",
  instagramUrl: "https://instagram.com/istanadegan",
  facebook: "Udien Barang Antique",
  address: "Plongkowati 1 No. 3, RT 04 / RW 13, Krobokan, Semarang Barat, Kota Semarang, Jawa Tengah 50141",
  gmapsQuery: "udien+barang+antique+krobokan+semarang+barat",
  gmapsUrl: "https://maps.google.com/?q=udien+barang+antique+krobokan+semarang+barat",
  totalPosts: "11.600+",
  totalFollowers: "25.800+",
  city: "Semarang Barat, Jawa Tengah"
};
